### PR TITLE
Corrected potential WebhookConfig issues.

### PR DESCRIPTION
**Pull request by accu-clw**
Hello :wave: 

On the back of looking at your [spatie/laravel-webhook-client](https://github.com/spatie/laravel-webhook-client) package, I was looking at this as an example implementation and believe there may be a couple of minor mistakes.

Please consider this PR as a potential fix.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you!

**Comment by mattvb91** [comment]
This isnt a major issue cause I caught version 3.0.2 breaking in my tests upgrading from 3.0.1 but wouldn't this config change be considered a breaking change so the versioning is off?

@accu-clw change fixed the issue for me by updating my config file to the correct model.

**Comment by freekmurze** [comment]
I'm sorry this broken your tests.

I'm thinking that the old version of the code was downright wrong, that's why I'm treating it as a bug fix, and not a breaking change.

If there's anything we can do, to improve let me know.

**Comment by accu-clw** [comment]
> This isnt a major issue cause I caught version 3.0.2 breaking in my tests upgrading from 3.0.1 but wouldn't this config change be considered a breaking change so the versioning is off?
> 
> @accu-clw change fixed the issue for me by updating my config file to the correct model.

Apologies if this broke for you (and any others!). I would agree with @freekmurze though, as the implementation was using an underlying library incorrectly.

**Comment by mattvb91** [comment]
yea no stress all good from my side just thought i'd point it out as there may be others with automatic dependabot updates coming with the same issue!

Thanks for the lib!

**Comment by colincameron** [comment]
For the benefit of anyone else who was bitten by this change causing Webhooks failures and is googling their error:

> Error: Call to undefined method Spatie\StripeWebhooks\ProcessStripeWebhookJob::storeWebhook() in file /app/vendor/spatie/laravel-webhook-client/src/WebhookProcessor.php on line 48

The above error is caused by the typo fix to src/StripeWebhooksController.php line 22 now using the correct config value, which was incorrectly set to `Spatie\StripeWebhooks\ProcessStripeWebhookJob::class` instead of `\Spatie\WebhookClient\Models\WebhookCall::class`

Fixing the config value at stripe-webhooks.php resolves this.

**Pull request merged**
